package com.example.domain.enumclass

enum class DeviceSharedPreferenceKey {
    DEVICE_INFORMATION,
    EMPTY_STRING,
    BLUETOOTH_DEVICE,
    USB_DEVICE,
    DISCONNECT_BLUTOOTH_DEVICE,
    DISCONNECT_USB_DEVICE,
    CURRENT_REGISTERED_DEVICE_TYPE,
    BINDING_BLUETOOTH_SERVICE,
    BINDING_USB_SERVICE,
    KEEP_BLUETOOTH_CONNECTION
}